books = [
    {
        "id": 1,
        "title": "Think Python",
        "author": "Allen B. Downey",
        "publisher": "O'Reilly Media",
        "published_date": "2012-01-01",
        "page_count": 224,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Django for Beginners",
        "author": "Markus K. Kuhnel",
        "publisher": "Packt Publishing",
        "published_date": "2012-01-01",
        "page_count": 320,
        "language": "English",
    },
    {
        "id": 3,
        "title": "FastAPI: Building Web APIs with FastAPI",
        "author": "Sebastián Ramírez",
        "publisher": "Packt Publishing",
        "published_date": "2022-01-01",
        "page_count": 320,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Python for Data Analysis",
        "author": "Wes McKinney",
        "publisher": "O'Reilly Media",
        "published_date": "2013-01-01",
        "page_count": 320,
        "language": "English",
    },
    {
        "id": 5,
        "title": "Python for Data Science",
        "author": "Wes McKinney",
        "publisher": "O'Reilly Media",
        "published_date": "2014-01-01",
        "page_count": 320,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Python for Data Visualization",
        "author": "Wes McKinney",
        "publisher": "O'Reilly Media",
        "published_date": "2015-01-01",
        "page_count": 320,
        "language": "English",
    },
]